# Site

title: RNetLogo
handouts:
  - worksheet.R
tag: v0.1
lesson: 3b
instructor: Kelly Hondula
authors:
  - Kelly Hondula

# Slides

slide_sorter:
  - intro
  - setup
  - modes
  - loadmodel
  - commands
  - report
  - reportwhile
  - simulation
  - plotresults
  - agents
  - patches
  - review

#####################################
# Only modify content above or risk #
# merge conflicts with upstream.    #
#####################################

# Style

styleurl: https://cdn.rawgit.com/sesync-ci/lesson-style/v1.2/docs
reveal: https://cdn.rawgit.com/hakimel/reveal.js/3.5.0

# Jekyll

markdown: kramdown
collections:
  - slides
